### ISSUE TITLE
Critères d'évaluation

### ISSUE THREAD

**Issue by wgrison** [etalab/matchSIRET#18]
Bonjour et merci pour ce travail. Quelques questions sur l'évaluation des performances :
1. La fonction [check_if_same_score](https://github.com/etalab/matchSIRET/blob/c62450cf27afb562e8c54eae501787efd7e38695/queries.py#L112) : si je comprends bien, la fonction retourne la liste des réponses en tête ayant le même score. Ce choix vient-il de cette réflexion : "il peut arriver que plusoieurs établissements d'entreprise répondent aux critères de recherche (par exemple, si vous avez spécifié une ville et un nom de groupe, et que plusieurs établissements de ce groupe se trouvent dans cette ville). Il faut alors renvoyer l'ensemble de ces résultats exacts (ce cas se pose assez peu dans notre base de données des restaurants)."
2. Si oui, pourquoi ne pas ajouter comme critère d'évaluation que tous les éléments retournés doivent aussi avoir le même SIREN (et un élément le même SIRET) ? 
3. Pour SIRETiser une base, on ne peut donc pas savoir si le bon SIRET est présent en top-1 de la liste retournée. Pourquoi ne pas ajouter une évaluation en top-1 stricte pour connaître la performance non pas en recherche mais en tant qu'enrichissement automatique de base ?
J'ai peut-être loupé une ligne de code qui répondrait déjà à mes questions.
Merci d'avance

**Comment by pedevineau** [comment]
Si toutes les questions ont été résolues, je ferme cette demande. N'hésitez pas à la rouvrir si nécessaire.
