### ISSUE TITLE
instance publique ?

### ISSUE THREAD

**Issue by joelgombin** [etalab/matchSIRET#20]
Bonjour,

existe-t-il une instance accessible publiquement pour tester ce service (je comprends bien que si l'usage devient significatif il vaut mieux déployer sa propre instance) ? 

Merci !

**Comment by pedevineau** [comment]
Bonjour,
Oui, une instance publique est prévue, mais seulement à des fins de démonstration (plutôt que d'opération). Il faudra malheureusement encore attendre un peu, d'autres tâches à plus haute priorité nous mobilisant dans l'immédiat. Je laisse l'issue ouverte jusque là.

**Comment by joelgombin** [comment]
D'accord, merci de la réponse !

**Comment by pedevineau** [comment]
Les fonctionnalités de recherche d'établissement sont progressivement fondues dans l'Annuaire des entreprises développé par la DINUM : https://annuaire-entreprises.data.gouv.fr/   
L'annuaire propose également une instance officielle d'API : https://api.gouv.fr/documentation/api-recherche-entreprises

Le code source derrière l'instance officielle de l'annuaire des entreprises est ouvert (en licence MIT), voir notamment le dépôt : https://github.com/etalab/annuaire-entreprises-search-api 

Les principales données nécessaires à une éventuelle réinstanciation de l'Annuaire, à savoir les données SIRENE géolocalisées sont ouvertes et maintenues à jour (d'autres données accessoires ne le sont pas) : https://files.data.gouv.fr/insee-sirene/

L'avenir du dépôt matchSIRET (maintenance ou dépréciation au profit de l'annuaire) sera clarifié dans les prochaines semaines. Je rouvrirai le ticket en fonction de ces décisions.
